version: '3.8'

services:
    localhost:
        container_name: postgres_db
        image: 'postgres:12'
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: 'savio_cubos'
            POSTGRES_PASSWORD: '12345'
            POSTGRES_DB: 'postgres'
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: {}
